### ISSUE TITLE
not works on ruby 1.9 bacause of RCov and Cucumber

### ISSUE THREAD

**Issue by dora2** [jlapier/Rails-CMS-Wiki-Forum#16]
I just tried this app at first time today.

$ rake db:create
rake aborted!
RCov only works on Ruby 1.8.x. You may want to use SimpleCov: https://github.com/colszowka/simplecov

then,gem simplecov ,bundle install and writing in spec/spec_helper.rb the below codes (a general solution for ruby1.9 switching to simplecov)  

require 'simplecov'
SimpleCov.start 'rails'

but the same error occurs.

Cucumber still calls RCov from somewhere else.(I don't know so much about cucumber and the settings).

**Comment by diatmpravin** [comment]
Time of bundle install, rcov.rake file generated at lib/task folder. remove this file.
